name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            
          - os: macos-latest
            target: x86_64-apple-darwin
            
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation tools
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Build
      run: |
        if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
        fi
        cargo build --release --target ${{ matrix.target }}

    - name: Create archive
      run: |
        cd target/${{ matrix.target }}/release
        tar -czf ../../../gitignore-${{ github.ref_name }}-${{ matrix.target }}.tar.gz gitignore
        cd ../../..

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gitignore-${{ matrix.target }}
        path: gitignore-${{ github.ref_name }}-${{ matrix.target }}.tar.gz

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          gitignore-x86_64-unknown-linux-gnu/gitignore-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
          gitignore-aarch64-unknown-linux-gnu/gitignore-${{ github.ref_name }}-aarch64-unknown-linux-gnu.tar.gz
          gitignore-x86_64-apple-darwin/gitignore-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz
          gitignore-aarch64-apple-darwin/gitignore-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false